spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/FLYWAY?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: flyway
        password: flyway-samples
        driverClassName: com.mysql.jdbc.Driver
        initialSize: 5
        maxActive: 10
        minIdle: 3
        maxWait: 30000
        timeBetweenEvictionRunsMillis: 30000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
#
#mybatis:
#    type-aliases-package: com.github.tonydeng.samples.flyway.mybaits.dao
#    type-handlers-package: com.github.tonydeng.samples.flyway.mybaits.dao
#    configuration:
#        map-underscore-to-camel-case: true
#        default-fetch-size: 100
#        default-statement-timeout: 30